# Ruff configuration
# See https://doc.astral.sh/ruff/configuration

[tool.ruff]
line-length = 120
target-version = "py37"
exclude = [
    ".venv",
    ".local",
    ".test/.local",
    ".cache",
]

[tool.ruff.format]
indent-style = "space"

[tool.ruff.lint]
extend-select = [
    "E",
    "F",
    "ANN",
    "W",
    "T",
    "COM",
    "RUF",
]
ignore = [
    "ANN002",
    "ANN003",
    "RUF100",
]

[tool.ruff.per-file-target-version]
"lizmap_server/context/qjazz.py" = "py312"

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "T201",
    "E501",
]
"test/*" = [
    "T201",
    "E501",
]
"lizmap_server/tooltip.py" = [
    "RUF001",
    "RUF002",
]


[tool.ruff.lint.isort]
#lines-between-types = 1
known-third-party = [
    "qgis",
]
#combine-as-imports = true
#split-on-trailing-comma = true
#multi-line-output = 3
#include-trailing-comma = true
#use-parentheses = true
#ensure-newline-before-comments = true

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = true
suppress-none-returning = true
suppress-dummy-args = true

[tool.qgis-plugin-ci]
plugin_path = "lizmap_server"
github_organization_slug = "3liz"
project_slug = "qgis-lizmap-server-plugin"
