name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - release-2_*
  pull_request:
    branches:
      - master
      - release-2_*

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

